### ISSUE TITLE
Histogram for 404 Responses

### ISSUE THREAD

**Issue by mikerg87** [stevedesmond-ca/LoadTestToolbox#12]
would be nice if there was a way to get a histogram or other visualization of responses received.  Yesterday, for example, I gave a bad URL to the tool to effectively load test the "404" page. wouldn't have to be graphical if it just output the results to the console

**Comment by stevedesmond-ca** [comment]
Sounds like it just needs to catch the other (non-200) response codes

**Comment by adam-kesy** [comment]
In that case you are not able to tell if the response is 200 (OK).
Therefore, you might be getting wrong load test results - you might think the endpoint responses fast but it is just because you are getting 401/403/500 etc.
Once you realize you need to authenticate, e.g. with a bearer token, you will start getting reliable results. On the other hand, you still not sure what response you are getting, you need to trust it is fine in that case, though.
Or am I missing something? I can see neither response code in chart nor any configuration options regarding that matter.

**Comment by SteveDesmond-ca** [comment]
Thanks for the feedback, I'm going to translate this request to a "new feature" issue in the next couple days.

**Comment by SteveDesmond-ca** [comment]
#149
