### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by SteveDesmond-ca** [SteveDesmond-ca/LoadTestToolbox#26]
It would be great if all the dependencies were automated!

**Comment by mchughmk** [comment]
This is a particular passion of mine.  Mind if I take it?

**Comment by mchughmk** [comment]
Just wanted to give an update on this.  I haven't forgotten about it, but it may need to be put on hold until some other things are tackled first since the earliest framework version available as a Docker image is `2.1`.  The `Microsoft.AspNetCore.SpaServices` library has been [obsolete since 2.1](https://github.com/dotnet/aspnetcore/issues/12890), so it's probably worth investigating using something like [ClearScript](https://github.com/microsoft/ClearScript) to run the JS code now.

**Comment by SteveDesmond-ca** [comment]
Switching to LiveCharts got rid of the Node dependency, so this is no longer needed.
